name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository }}/boutique-backend:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/boutique-frontend:latest

  deploy:
    needs: build-and-push # Ce job ne commence que si le build est réussi
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3 # Utilise l'action SSH pour la connexion
        with:
          host: ${{ secrets.SERVER_HOST }} # Adresse IP du serveur
          username: ${{ secrets.SERVER_USER }} # Utilisateur admin
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Ta clé privée id_rsa_github
          script: |
            # 1. Se connecter au registre pour accéder aux images privées
            echo "${{ secrets.GHCR_TOKEN_READ }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # 2. Télécharger les dernières versions des images
            docker pull ghcr.io/${{ github.repository }}/boutique-backend:latest
            docker pull ghcr.io/${{ github.repository }}/boutique-frontend:latest

            # 3. Arrêter et supprimer les anciens conteneurs s'ils existent
            docker stop boutique-back boutique-front || true
            docker rm boutique-back boutique-front || true

            # 4. Lancer les nouveaux conteneurs
            docker run -d --name boutique-back -p 8000:8000 ghcr.io/${{ github.repository }}/boutique-backend:latest
            docker run -d --name boutique-front -p 80:80 ghcr.io/${{ github.repository }}/boutique-frontend:latest
